name: 'Cancel Workflow Action for duplicate jobs'
description: 'This Action will cancel the duplicate jobs'
author: vishnudxb
branding:
  icon: 'stop-circle'  
  color: 'red'
inputs:
  repo:
    description: 'Repo details: for eg: octocat/hello-world'
    required: true  
  workflow_id:
    description: 'Github Action Workflow ID'
    required: true
  access_token:
    description: 'Your GitHub Access Token, defaults to: {{ github.token }}'
    default: '${{ github.token }}'
    required: false
  branch_name:
    description: 'Specify the branch name you want to check if the job is running'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.workflow_id }}
    - ${{ inputs.access_token }}
    - ${{ inputs.branch_name }}
